### ISSUE TITLE
Skills matrix UX

### ISSUE THREAD

**Issue by bettiolo** [tes/app-skills-matrix#162]
There is a legend at the top, we should make it clickable to filter down the matrix and see only the matching ones:

<img width="773" alt="screen shot 2017-10-19 at 20 45 56" src="https://user-images.githubusercontent.com/1333608/32011220-064f507e-b9ac-11e7-894d-6a822fac4641.png">

**Comment by charlieharris1** [comment]
@rnewstead1 it'd be great if we could add a clear filter button. @dmorgantini pointed out that clicking a filter a second time clears it, but I think having a clear button may be a better experience.

**Comment by rnewstead1** [comment]
@charlieharris1 we _could_ do that... I am concerned that it would clutter the UI and as @dmorgantini pointed out you can clear the filter by clicking on it. Can we put it out without the extra button and get people to use it and see what they think?

**Comment by dmorgantini** [comment]
I think that's fine.  We'll need to figure out something better to do with the dangling thing on the right (new skill).  Possibly just get rid of it?

**Comment by charlieharris1** [comment]
🚢
